apiVersion: apps/v1
kind: Deployment
metadata:
  name: eks-demo-app-deployment
  labels:
    app: eks-demo-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: eks-demo-app
  template:
    metadata:
      name: eks-demo-app-pod
      labels:
        app: eks-demo-app
    spec:
      containers:
      - name: eks-demo-app-container
        image: 886602151343.dkr.ecr.us-west-2.amazonaws.com/eksdemo:latest
        imagePullPolicy: Always
        livenessProbe:
          httpGet:
            path: /healthcheck
            port: 3000
