apiVersion: v1
kind: Service
metadata:
  name: eks-demo-service-np
  labels:
    name: eks-demo-app-deployment
    app: eks-demo-app
spec:
  type: NodePort
  selector:
    app: eks-demo-app
  ports:
    - protocol: TCP
      port: 3000
      nodePort: 30072
